' ******************************************************************************
' C:\Users\maxwell.wong\AppData\Local\Temp\swx6116\Macro1.swb - macro recorded on 04/29/20 by maxwell.wong
' ******************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

' New Document
Dim swSheetWidth As Double
swSheetWidth = 0
Dim swSheetHeight As Double
swSheetHeight = 0
Set Part = swApp.NewDocument("C:\Program Files\SOLIDWORKS Corp 2020\SOLIDWORKS\lang\english\Tutorial\part.prtdot", 0, swSheetWidth, swSheetHeight)
Dim swPart As PartDoc
Set swPart = Part
swApp.ActivateDoc2 "Part1", False, longstatus
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Top", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SetUserPreferenceToggle(swUserPreferenceToggle_e.swSketchAddConstToRectEntity, swUserPreferenceOption_e.swDetailingNoOptionSpecified, True)
boolstatus = Part.Extension.SetUserPreferenceToggle(swUserPreferenceToggle_e.swSketchAddConstLineDiagonalType, swUserPreferenceOption_e.swDetailingNoOptionSpecified, True)
Dim vSkLines As Variant
vSkLines = Part.SketchManager.CreateCenterRectangle(0, 0, 0, 2.70489732505521E-02, -3.45277732516531E-02, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 2.70489732505521E-02, 0, -9.33913539373906E-03, False, 0, Nothing, 0)
Dim myDisplayDim As Object
Set myDisplayDim = Part.AddDimension2(5.33746124477232E-02, 0, -3.74493706434019E-03)
Part.ClearSelection2 True
Dim myDimension As Object
Set myDimension = Part.Parameter("D1@Sketch1")
myDimension.SystemValue = 0.01
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 3.09806320432903E-03, 0, -5.04084520581232E-03, False, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(1.80939857898413E-03, 0, -0.007457091378334)
boolstatus = Part.Extension.SelectByID2("D1@Sketch1@Part1.SLDPRT", "DIMENSION", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D2@Sketch1")
myDimension.SystemValue = 0.01
Part.ClearSelection2 True

' Named View
Part.ShowNamedView2 "*Trimetric", 8
Part.ViewZoomtofit2

' Zoom In/Out (MouseWheel)
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.Scale2 = 6.57563687358462
Dim swTranslation() As Double
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 1.52156523442546E-02
swTranslation(1) = 6.5499483614815E-04
swTranslation(2) = 3.99643815961353E-04
Dim swTranslationVar As Variant
swTranslationVar = swTranslation
Dim swMathUtils As Object
Set swMathUtils = swApp.GetMathUtility()
Dim swTranslationVector As MathVector
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 5.47969739465385
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 1.77565667225224E-02
swTranslation(1) = 5.45829030123463E-04
swTranslation(2) = 3.33036513301128E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 6.60204505379982
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 1.35203022661906E-02
swTranslation(1) = -1.41856606281466E-02
swTranslation(2) = 4.01248811206178E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 7.95427114915641
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 7.87166144441434E-03
swTranslation(1) = -3.20025318166863E-02
swTranslation(2) = 4.83432302658046E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 9.5834592158511
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 8.61804689679713E-04
swTranslation(1) = -5.34686416823967E-02
swTranslation(2) = 5.82448557419332E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 7.98621601320925
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 5.79502701037664E-03
swTranslation(1) = -4.45572014019973E-02
swTranslation(2) = 4.85373797849443E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 6.65518001100771
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 9.90604561095742E-03
swTranslation(1) = -0.037131001168331
swTranslation(2) = 4.04478164874536E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 8.0182891698888
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = -8.39834649938328E-03
swTranslation(1) = -0.046029826872855
swTranslation(2) = 4.87323090210285E-04
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Dim myFeature As Object
Set myFeature = Part.FeatureManager.FeatureExtrusion2(True, False, False, 0, 0, 0.01, 0.01, False, False, False, False, 1.74532925199433E-02, 1.74532925199433E-02, False, False, False, False, True, True, True, 0, 0, False)
Part.SelectionManager.EnableContourSelection = False
End Sub
